### ISSUE TITLE
Please add a readme with a guide!

### ISSUE THREAD

**Issue by chricker05** [bradrn/exSCA-cpp#3]
I find that most of this is pretty much the same as Mark Rosenfelder's tool, but there are some subtle differences. I'm not sure where a guide is but a simple .txt would be great.
Features such as gemination and degemination remain elusive without any such guide.

**Comment by bradrn** [comment]
Thanks for your interest @chricker05! The only documentation is here: http://www.incatena.org/viewtopic.php?f=5&t=44120. I do not plan to add any more documentation, as I am not interested in maintaining exSCA-cpp any more. This is mostly because I am currently working on a new sound change applier, which should be a big improvement over exSCA-cpp; I should be able to release a first version in the next couple of months (though take this with a huge grain of salt, I am starting university in a couple of weeks which means I may not have as much time to work on it as I want). In the meantime, feel free to ask questions here and I will try to answer them as best as I can.

**Comment by chricker05** [comment]
Oh! That's great, thank you!

Can't wait for the new SCA!

**Comment by bradrn** [comment]
@chricker05 Just want to let you know the SCA I mentioned is now available at https://github.com/bradrn/brassica. I will not be working on exSCA-cpp any more except for urgent bugfixes.
